spring:
  application:
    name: spring-ai-mcp-server
  ai:
    mcp:
      server:
        name: spring-ai-mcp-server-sse
        version: 1.0.0
        sse-endpoint: /sse
        type: async

  mail:
    host: smtp.163.com
    port: 465
    username: 123@163.com
    password: 123456  # 注意：这里通常是邮箱授权码，不是登录密码
    protocol: smtp
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
          ssl:
            enable: true


logging:
  level:
    root: info
server:
  port: 8080

